#ifndef MULTIBOOT_H
#define MULTIBOOT_H

#define MULTIBOOT_HEADER_MAGIC      0xe85250d6
#define MULTIBOOT_BOOTLOADER_MAGIC  0x36d76289
#define MULTIBOOT_ARCHITECTURE_I386 0
#define MULTIBOOT_HEADER_TAG_END    0

#endif /* MULTIBOOT_H */
